amcl:
  ros__parameters:
    use_sim_time: false
    scan_topic: /scan
    odom_topic: /odom
    base_frame_id: base_link
    map_frame: map
    min_particles: 100  # Minimum number of particles for localization
    max_particles: 5000  # Maximum number of particles for localization
    update_min_d: 0.2  # Minimum distance (meters) to update the filter
    update_min_a: 0.1  # Minimum angle (radians) to update the filter
    resample_interval: 1
    transform_tolerance: 0.1  # Time to wait for transforms (seconds)
    laser_min_range: 0.1  # Minimum range for the Lidar
    laser_max_range: 12.0  # Maximum range for the Lidar
    laser_model_type: likelihood_field
    odom_model_type: diff  # Differential drive robot

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: False
      min_vel_x: 0.05  # Set a minimum velocity to avoid stalling
      max_vel_x: 0.26
      min_vel_theta: 0.1  # Ensure small angular adjustments are allowed
      max_vel_theta: 1.82
      critics: 
        - "Oscillation"  # Penalize oscillatory behaviors
        - "ObstacleFootprint"  # Check for obstacles in the path
        - "GoalAlign"  # Align the robot to the goal
        - "PathAlign"  # Align the robot to the path
        - "PathDist"  # Evaluate distance from the path
        - "GoalDist"  # Evaluate distance to the goal
      PathAlign.scale: 32.0
      GoalAlign.scale: 24.0
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      ObstacleFootprint.scale: 1.0  # Increase emphasis on avoiding obstacles
      ObstacleFootprint.radius: 0.2  # Reduce footprint radius for tighter spaces

dwb_controller:
  ros__parameters:
    min_obstacle_dist: 0.3  # Minimum allowed distance from obstacles
    inflation_radius: 0.5  # Safety buffer around obstacles
    robot_radius: 0.2  # Robot footprint radius
    prune_plan: true  # Prune path to improve performance
    debug_trajectory_details: false
    vx_samples: 20  # Number of velocity samples in x-direction
    vy_samples: 0  # No lateral velocity for differential drive
    vtheta_samples: 20  # Number of angular velocity samples
    acc_lim_x: 1.0  # Maximum linear acceleration
    acc_lim_theta: 3.2  # Maximum angular acceleration
    max_vel_x: 0.26
    max_vel_theta: 1.82
