amcl:
  ros__parameters:
    use_sim_time: false
    scan_topic: /scan
    odom_topic: /odom
    base_frame_id: base_link
    map_frame: map
controller_server:
  ros__parameters:
    linear:
      max_velocity: 0.5  # Crește viteza liniară maximă la 1.0 m/s
      min_velocity: -0.5
    angular:
      max_velocity: 1.0  # Crește viteza unghiulară maximă la 2.0 rad/s
      min_velocity: -1.0
dwb_controller:
  ros__parameters:
    min_obstacle_dist: 0.5  # Scade distanța minimă la 0.3 metri
    inflation_radius: 0.6   # Reduce zona de siguranță la 0.5 metri
    robot_radius: 0.5
