slam_toolbox:
  ros__parameters:
    slam_mode: "mapping"  # Use live mapping mode
    resolution: 0.05      # Map resolution in meters per cell
    map_update_interval: 2.0  # Interval for updating the map (in seconds)
    max_laser_range: 12.0  # Maximum range of your Lidar
    transform_publish_period: 0.05  # Frequency of TF updates
    scan_topic: "/scan"  # Lidar topic
    map_frame: "map"
    base_frame: "base_link"
    odom_frame: "odom"
    use_sim_time: false  # Adjust if simulating
