amcl:
  ros__parameters:
    use_sim_time: false
    scan_topic: /scan
    odom_topic: /odom
    base_frame_id: base_link
    map_frame: map
controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
