slam_toolbox:
  ros__parameters:
    slam_mode: "mapping"
    map_file_name: "my_map"
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.2  # Salvează harta la fiecare 200ms
    save_map_timeout: 5.0  # Salvează harta la fiecare 5 secunde
